config/routes.rb
Cla::Application.routes.draw do
	root :to => "pages#index"

	resources :checklists
	
	match 'checklists/:id/checkoff' => 'checklists#checkoff'
	match 'checklists/:id/finish' => 'checklists#finish'
	match 'checklists/:id/abandon' => 'checklists#abandon'
	match 'about' => 'pages#about'
	match 'samples' => 'pages#samples'
	
	devise_for :users,
		:controllers => { :sessions => 'devise/sessions'},
		:skip => [:sessions] do
			get '/login' => 'devise/sessions#new', :as => :new_user_session
			post '/login' => 'devise/sessions#create', :as => :user_session
			get '/logout' => 'devise/sessions#destroy', :as => :destroy_user_session
	end

	
	
	
	
	
	
	
	
	
	
  
end

app/models/checklist.rb
class Checklist < ActiveRecord::Base
	validates_presence_of :list, :message => 'can\'t be blank'
	
	# we split off a bunch of stuff automagically from the list body to make it easier to use for the user
	def self.get_title_from_list list
		@lines = list.split("\n")
		return @lines[0]
	end
	
	# the last line of a checklist should contain emails to send the checklist to.
	# if it doesn't, then it's the last checklist item
	def self.get_emails_from_list list
		if(list.kind_of?(Array))
			lastline = list.last
		else
			lastline = list.split("\n").last
		end
		
		return is_email_list lastline.strip
	end
	
	# is a list of emails actually emails?
	def self.is_email_list emails
		#if it's a list, check each one
		emails = emails.split(/, */ )
		if(emails.kind_of?(Array))
			emails.each do |email|
				unless is_email email
					emails = nil
					break # since we don't care if more than one entry is bad
				end
			end
			
			unless emails.nil?
				emails = emails.join(', ')
			end
		else
			unless is_email emails
				emails = nil
			end
		end
		
		return emails
	end
	
	# check if a little email is valid
	def self.is_email email
		return email =~ /^[a-zA-Z][\w\.-]*[a-zA-Z0-9]@[a-zA-Z0-9][\w\.-]*[a-zA-Z0-9]\.[a-zA-Z][a-zA-Z\.]*[a-zA-Z]$/ ? true : false
	end
	
	# pull out parts from the list we don't need
	def self.prepare_list checklist
		# make an array
		checklist.list = checklist.list.lines.to_a
		
		# the first line is always the title
		checklist.list = checklist.list[1..-1]
		
		# the last line might be emails, which is optional
		checklist.list = ( ( get_emails_from_list checklist.list) != '' ) ? checklist.list[0..-2] : checklist.list
		
		# remove the optional line numbers the user might enter so we can build it out in the view
		# make it an array so we can output cleanly in the view		
		checklist.list.each_with_index do |item,i|
			checklist.list[i] = item.gsub(/[0-9]+[ ]?[\.]?[\-]?/,'')
		end
		
		return checklist
	end
	
	# show start only of checklist for display when listed with other checklists
	def self.prepare_lists checklists
		checklists.each_with_index do |list,i|
			checklists[i] = Checklist.prepare_list list
			checklists[i].list = checklists[i].list[1..3]
		end
		
		return checklists
	end
	
	# remove blank lines from the list
	def self.clean_up_list list
		return list.split("\n").delete_if {|line| line.blank?}.join("\n")
	end
end

app/controllers/checklists_controller.rb
require 'yaml'
class ChecklistsController < ApplicationController
	#login required
	before_filter :authenticate_user!
		
	# GET /checklists
	# GET /checklists.xml
	def index
		@checklists = Checklist.all(:select=>'id,list,title,updated_at',:order=>'updated_at DESC')
		
		@checklists = Checklist.prepare_lists @checklists
		
		respond_to do |format|
			format.html # index.html.erb
			format.xml { render :xml => @checklists }
		end
	end
  
	# what happens when a user checks off a checklist item
	def checkoff
		if request.xhr?
			# Events we need to capture: start a new instance, update existing instance, email complete!
			
			# Event: Start a new instance
			# an instance of the checklist is one that is filled out by this user, isn't complete, and is the most recent
			# they will only have one active instance at any time
			# if it doesn't exist, create it			
			instance = Instance.get_or_create params[:id]
			
			# Update what item was just checked or checked off
			instance.finished_items = Instance.update_finished_items instance.id, instance.finished_items, params[:item]			
			
			respond_to do |format|
				format.json { render :json => instance, :template => 'blank' }
			end
		end
	end
	
	# when all items done, they can finish it
	def finish		
		instance = Instance.get_or_create params[:id]
		title = Checklist.get_title_from_list instance.list
		
		# send email
		instance.emails.split(',').each do |email|
			email.strip!
			Notifier.checklist_finished(title, email).deliver if Checklist.is_email email
		end
		
		# mark as finished
		Instance.finish Instance.get_or_create params[:id]
		
		# send em!
		flash[:success] = 'We emailed your team (' + instance.emails + ') to let them know the checklist was completed.'
		redirect_to checklists_path
	end

	# GET /checklists/1
	# GET /checklists/1.xml
	def show
		# load up the checklist in question, which we have
		@checklist = Checklist.prepare_list Checklist.find params[:id]
		
		# pull any previous instances to show to the user in a history
		@previous = Instance.get_previous params[:id]
		
		# get an instance if we have one
		@instance = Instance.exists params[:id]
		@instance = @instance ? (Checklist.prepare_list @instance) : @instance;
		
		respond_to do |format|
			format.html # show.html.erb
			format.xml  { render :xml => @checklist }
		end
	end
	
	# if filling out an instance you can just give up
	def abandon
		@checklist = Checklist.find params[:id]
		@instance = Instance.get_or_create params[:id]
		@instance.destroy
		
		respond_to do |format|
			format.html { redirect_to(@checklist) }
			format.xml  { head :ok }
		end
	end

	# GET /checklists/new
	# GET /checklists/new.xml
	def new
		@checklist = Checklist.new
		
		respond_to do |format|
			format.html # new.html.erb
			format.xml  { render :xml => @checklist }
		end
	end

	# GET /checklists/1/edit
	def edit
		@checklist = Checklist.find(params[:id])
	end

	# POST /checklists
	# POST /checklists.xml
	def create
		@checklist = Checklist.new(params[:checklist])
		
		respond_to do |format|
			if @checklist.save
				flash[:success] = 'Your checklist was created!'
				format.html { redirect_to(@checklist) }
				format.xml  { render :xml => @checklist, :status => :created, :location => @checklist }
			else
				format.html { render :action => "new" }
				format.xml  { render :xml => @checklist.errors, :status => :unprocessable_entity }
			end
		end
	end

	# PUT /checklists/1
	# PUT /checklists/1.xml
	def update
		@checklist = Checklist.find(params[:id])
		
		# trim blank lines
		params[:checklist][:list] = Checklist.clean_up_list params[:checklist][:list]
		
		# we take the first line and make that the title
		params[:checklist][:title] = Checklist.get_title_from_list params[:checklist][:list]
		
		# we take thelast line to get the email recipients
		params[:checklist][:emails] = Checklist.get_emails_from_list params[:checklist][:list]
		
		respond_to do |format|
			if @checklist.update_attributes(params[:checklist])
				flash[:success] = 'Your checklist template was saved.'
				format.html { redirect_to(@checklist) }
				format.xml  { head :ok }
			else
				format.html { render :action => "edit" }
				format.xml  { render :xml => @checklist.errors, :status => :unprocessable_entity }
			end
		end
	end

	# DELETE /checklists/1
	# DELETE /checklists/1.xml
	def destroy
		@checklist = Checklist.find(params[:id])
		@checklist.destroy
		
		respond_to do |format|
			format.html { redirect_to(checklists_url) }
			format.xml  { head :ok }
		end
	end
end

app/helpers/checklists_helper.rb
module ChecklistsHelper
end

app/views/checklists/_form.html.haml
= form_for(@checklist) do |f|
	- if @checklist.errors.any?
		#error_explanation
		%h2
			= pluralize(@checklist.errors.count, "error")
			prohibited this checklist from being saved:
	
		%ul
		- @checklist.errors.full_messages.each do |msg|
			%li= msg

	.field
		= f.label :title 
		%br
		= f.text_field :title
	
	.field
		= f.label :list
		%br
		= f.text_area :list
	
	.actions
		= f.submit

app/views/checklists/edit.html.haml
- content_for(:title, 'Edit your checklist')
= render :partial => 'shared/flash', :locals => {:flash => flash }

.grid_7
	%br

	- form_for @checklist do
	
		.textarea
			= text_area_tag('checklist[list]',@checklist.list,:id=>'ChecklistBody',:rows=>6,:cols=>25,:class=>'checklistbox')
			%br
		
		#SubmitArea
			#SubmitAreaControls
				= submit_tag 'Save', :class=>'button'
				= link_to 'Cancel', @checklist, :title=>'Return to checklist listing page'
			%br{:clear=>'all'}

.grid_5
	%br
	#PreviewBox.leftspacer

app/views/checklists/index.html.haml
- content_for(:title, 'Listing checklists')
= render :partial => 'shared/flash', :locals => {:flash => flash }

.grid_8
	- @checklists.each do |checklist|
		%h2.checklist_title
			= link_to checklist.title, checklist, :title=>'See the whole checklist'
			%span
				= link_to 'Edit', edit_checklist_path(checklist), :title=>'There is one template per list, but many instances.'
			
		%span.subnote
			template updated
			= time_ago_in_words checklist.updated_at
			ago
			= link_to 'Delete', checklist, :confirm => 'Are you sure?', :method => :delete, :title=> 'There is no undo'
			
		%ol
			- checklist.list.each do |item|
				%li
					= item
					
.grid_4
	%p 
		= link_to 'New Checklist', new_checklist_path
		
	%h2 Users

app/views/checklists/new.html.haml
- content_for(:title, 'Create new checklist')
.grid_12
	%h1
		= yield(:title)
	
	= render 'form'

	= link_to 'Back', checklists_path

app/views/checklists/show.html.haml
- content_for(:title, @checklist.title)
= render :partial => 'shared/flash', :locals => {:flash => flash }

:javascript
	function getCheckOffPath(id) {
		return '#{url_for(:action=>'checkoff',:controller=>'checklists', :id=>@checklist.id)}?item='+id;
	}

.grid_8
	%h2.checklist_title
		= h yield(:title)
		- if !@instance
			%span#EditControl
				= link_to 'Edit', edit_checklist_path(@checklist), :title=>'There is one template per list, but many instances.'
	
	- if @instance
		#AbandonBox
			%p
				Last updated by you #{time_ago_in_words @instance.updated_at} ago
				(#{ link_to 'abandon', { :action=>'abandon', :id=>@checklist.id}, :confirm=>'Are you sure?', :title=>'Delete what you have filled out and start over with the latest template'}):

	#AltAbandonBox(style="display:none")
		%p
			Last updated by you
			%span.time_ago_in_words
			ago
			(#{ link_to 'abandon', { :action=>'abandon', :id=>@checklist.id}, :confirm=>'Are you sure?', :title=>'Delete what you have filled out and start over with the latest template' }):
	
	- if @instance and @checklist.list != @instance.list
		#Flash.notice.persist
			%p
				The checklist template has changed since you started checking it off. You will have to
				= link_to 'abandon', { :action=>'abandon', :id=>@checklist.id }, :title=>'Delete what you have filled out and start over with the latest template'
				or finish this instance to use the latest version.
	
	%ol{:title=>"The checklsit items",:id=>"the_checklist"}
		- (@instance || @checklist).list.each_with_index do |item, i|
			%li(id="li_#{i.to_s}")
				= check_box_tag 'item_'+(i.to_s), 1, (true if @instance and @instance.finished_items and @instance.finished_items.include?(i.to_s))
				%label{:for=>"item_#{i.to_s}",:id=>"#{'label_'+i.to_s}",:class=>"itemlabel #{'strikeout' if @instance and @instance.finished_items and @instance.finished_items.include?(i.to_s)}"}
					= item 
				%span{:id=>"loader_#{i.to_s}",:style=>"display:none"}
					= image_tag 'loader-dots.gif'
	
	#FinishedBlock{:style=>"#{(@instance and @instance.finished_items and @instance.finished_items.count == @checklist.list.count) ? 'display:block' : 'display:none'}"}
		%span#finishloader(style="display:none;")
			= image_tag 'loader-dots.gif', :title=>'loading...', :alt=>'loading...'
			
		%span#finishbar
			= link_to 'Finish this checklist', { :action=>'finish', :id=>@checklist.id }, :class=>'yo'
			= ('by emailing ' + @checklist.emails) unless @checklist.emails.nil? || @checklist.emails.empty?

.grid_4
	.leftspacer
		%h2(title="We store instance history for the last two weeks")
			Last two weeks:
		
		%p
			- @previous.each do |old_instance|
				jemond #{time_ago_in_words old_instance.updated_at} ago
				%br